name: Build And Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: euleros-2.10.1

    steps:
    - uses: checkout-action@0.0.1
      
    - name: Build
      run:  cd repo_workspace && mkdir build && cd build && cmake .. && make -j4

    - name: Test
      run: cd repo_workspace && cd build && make test
      